### PR TITLE
Internship 84702

### PR DESCRIPTION
**Pull request by LisaPost**
Login Tests

### CODE REVIEW

**Comment by LisaPost** [comment]
Hi Alex! Could you please give me some advice here? 
I have to cover these acceptance criteria: 
User should be able to log in with the updated email and the old email should not work
User should be able to login with the updated password and the old password should not work
So that I need my initial username(email address) and password being set before any test will run, 
I'm trying to implement the following:
before any test my email is updated in DB (that seems to work fine)
before any test my password is reset via UI (that i think breaks all tests) 
And also i have concerns about posting credentials into test, is there a secure way to do it?
Thanks in advance!

**Comment by Berichicko** [comment]
You got this problem, please correct it.

image

HINT

Did you connect the driver?

No Suitable Driver Found For JDBC

https://www.javatpoint.com/no-suitable-driver-found-for-jdbc

**Comment by LisaPost** [comment]
thanks for your hint)
also made changes in OutlookEmailAutomation class
but still got: 
java.lang.NullPointerException: Cannot invoke "stepDefinitions.BaseDefinition.pickBrowser(String)" because "this.baseDefinition" is null
	at stepDefinitions.OutlookEmailAutomation.navigateToResetLink(OutlookEmailAutomation.java:25)
	at stepDefinitions.LoginStepDefinitions.iNavigateToResetPasswordLinkInMyEmail(LoginStepDefinitions.java:99)
	at ✽.I navigate to Reset password link in my email

how can i manage this error?

**Comment by Berichicko** [comment]
> thanks for your hint) also made changes in OutlookEmailAutomation class but still got: java.lang.NullPointerException: Cannot invoke "stepDefinitions.BaseDefinition.pickBrowser(String)" because "this.baseDefinition" is null at stepDefinitions.OutlookEmailAutomation.navigateToResetLink(OutlookEmailAutomation.java:25) at stepDefinitions.LoginStepDefinitions.iNavigateToResetPasswordLinkInMyEmail(LoginStepDefinitions.java:99) at ✽.I navigate to Reset password link in my email
> 
> how can i manage this error?

Hi dear Yelyzaveta

You got this problem, please correct it.

image

HINT

Add **BaseDefinition.getThreadLocal()**

```
package stepDefinitions;

import org.openqa.selenium.WebDriver;

import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.search.FromTerm;
import java.net.MalformedURLException;
import java.util.Properties;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class OutlookEmailAutomation {


    public void navigateToResetLink(String resetLink) throws MalformedURLException {

        if (resetLink != null) {
            BaseDefinition.getThreadLocal().get(resetLink);
            switchToNewTabOrWindow();
        } else {
            System.err.println("Reset link is null. Cannot navigate");
        }

    }
    public static String extractResetLinkFromEmail(String userEmail) {
        try {
            Properties props = new Properties();
            props.setProperty("mail.store.protocol", "imaps");
            Session session = Session.getInstance(props);

            Store store = session.getStore("imaps");
            store.connect("outlook.office365.com", "yelyzaveta.postnova@testpro.io", "stPGYWcp8TWf");

            Folder inbox = store.getFolder("INBOX");
            inbox.open(Folder.READ_ONLY);

            Message[] messages = inbox.search(new FromTerm(new InternetAddress(userEmail)), inbox.getMessages());

            for (Message message : messages) {
                if (!message.isSet(Flags.Flag.SEEN)) {
                    String content = getTextFromMessage(message);

                    String resetLink = extractResetLink(content);
                    if (resetLink != null) {
                        return resetLink;
                    }
                }
            }

            inbox.close(false);
            store.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    private static String getTextFromMessage(Message message) throws Exception {
        Object content = message.getContent();
        if (content instanceof String) {
            return (String) content;
        } else if (content instanceof Multipart) {
            StringBuilder sb = new StringBuilder();
            Multipart multipart = (Multipart) content;
            for (int i = 0; i < multipart.getCount(); i++) {
                BodyPart bodyPart = multipart.getBodyPart(i);
                sb.append(bodyPart.getContent().toString());
            }
            return sb.toString();
        }
        return null;
    }

    private static String extractResetLink(String content) {
        Pattern pattern = Pattern.compile("(?<=href=\")[^\"]+");
        Matcher matcher = pattern.matcher(content);

        if (matcher.find()) {
            return matcher.group();
        }
        return null;
    }
    private void switchToNewTabOrWindow() {
        Set<String> windowHandles = BaseDefinition.getThreadLocal().getWindowHandles();
        for (String windowHandle : windowHandles) {
            BaseDefinition.getThreadLocal().switchTo().window(windowHandle);
        }
    }
}
```

**Comment by LisaPost** [comment]
Hi Alex! I've added BaseDefinition.getThreadLocal(), and also JavascriptExecutor, to OutlookEmailAutomation class
but now i have error with opening Reset Password link, so test is searching the Web element on page that is not actually opened
Знімок екрана (24)

Could you please have a look at this issue?
Thanks again!

**Comment by Berichicko** [comment]
> Hi Alex! I've added BaseDefinition.getThreadLocal(), and also JavascriptExecutor, to OutlookEmailAutomation class
> but now i have error with opening Reset Password link, so test is searching the Web element on page that is not actually opened

Hi Yelyzaveta

HINT


```
package stepDefinitions;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;

import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.search.FromTerm;
import java.net.MalformedURLException;
import java.util.Properties;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class OutlookEmailAutomation {

    public void navigateToResetLink(String resetLink) throws MalformedURLException {
        System.out.println("Navigating to reset link: " + resetLink);
        if (resetLink != null) {
            System.out.println("Reset link is not null.");
            WebDriver driver = BaseDefinition.getThreadLocal();
            System.out.println("WebDriver obtained from BaseDefinition.getThreadLocal().");
            JavascriptExecutor jsExecutor = (JavascriptExecutor) driver;
            jsExecutor.executeScript("window.open('" + resetLink + "', '_self');");
            System.out.println("Executing JavaScript to open link in new tab.");
            switchToNewTabOrWindow();
        } else {
            System.err.println("Reset link is null. Cannot navigate.");
        }
    }

    public static String extractResetLinkFromEmail(String userEmail) {
        try {
            System.out.println("Extracting reset link from email for user: " + userEmail);
            Properties props = new Properties();
            props.setProperty("mail.store.protocol", "imaps");
            Session session = Session.getInstance(props);

            Store store = session.getStore("imaps");
            store.connect("outlook.office365.com", "yelyzaveta.postnova@testpro.io", "stPGYWcp8TWf");

            Folder inbox = store.getFolder("INBOX");
            inbox.open(Folder.READ_ONLY);

            Message[] messages = inbox.search(new FromTerm(new InternetAddress(userEmail)), inbox.getMessages());

            for (Message message : messages) {
                if (!message.isSet(Flags.Flag.SEEN)) {
                    System.out.println("Processing unseen message.");
                    String content = getTextFromMessage(message);
                    String resetLink = extractResetLink(content);
                    if (resetLink != null) {
                        System.out.println("Reset link found: " + resetLink);
                        return resetLink;
                    }
                }
            }

            inbox.close(false);
            store.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    private static String getTextFromMessage(Message message) throws Exception {
        Object content = message.getContent();
        if (content instanceof String) {
            return (String) content;
        } else if (content instanceof Multipart) {
            StringBuilder sb = new StringBuilder();
            Multipart multipart = (Multipart) content;
            for (int i = 0; i < multipart.getCount(); i++) {
                BodyPart bodyPart = multipart.getBodyPart(i);
                sb.append(bodyPart.getContent().toString());
            }
            return sb.toString();
        }
        return null;
    }

    private static String extractResetLink(String content) {
        Pattern pattern = Pattern.compile("(?<=href=\")[^\"]+");
        Matcher matcher = pattern.matcher(content);

        if (matcher.find()) {
            return matcher.group();
        }
        return null;
    }

    private void switchToNewTabOrWindow() {
        WebDriver driver = BaseDefinition.getThreadLocal();
        Set<String> windowHandles = driver.getWindowHandles();
        for (String windowHandle : windowHandles) {
            driver.switchTo().window(windowHandle);
        }
    }
}
```
**Navigating to reset link: null**

image

**Error in extracting email content:** Verify if your code correctly extracts the content of the email. The getTextFromMessage method should accurately extract the email's text content so that the password reset link can be found.

**Issues with the regular expression:** Check if your regular expression correctly extracts the link from the email content. Perhaps the pattern doesn't match the structure of the link in the email.

**Pull request closed without merging**
